steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/gia-v2-batch-audio-segmentation-service/audio-segmentation-service:v1.5 .
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/gia-v2-batch-audio-segmentation-service/audio-segmentation-service:v1.5'