steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/gia-v2-batch-enrichment-service/batch-enrichment-service:v1.0 .
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/gia-v2-batch-enrichment-service/batch-enrichment-service:v1.0'